TRUNCATE table account;
INSERT INTO account(id, acc_type_id, entity_id, name, code, description, d_created, parent, children) values (1, 5, 1,  'Cash',  '',  '',  '2012-08-22', , );
INSERT INTO account(id, acc_type_id, entity_id, name, code, description, d_created, parent, children) values (2, 10, 1,  'Room Sales',  '',  '',  '2012-08-22', , );
INSERT INTO account(id, acc_type_id, entity_id, name, code, description, d_created, parent, children) values (3, 10, 1,  'Restaurant Sales',  '',  '',  '2012-08-22', , );
INSERT INTO account(id, acc_type_id, entity_id, name, code, description, d_created, parent, children) values (4, 10, 1,  'Laundry Sales',  '',  '',  '2012-08-22', , );
INSERT INTO account(id, acc_type_id, entity_id, name, code, description, d_created, parent, children) values (5, 10, 1,  '5% Tax',  '',  '',  '2012-08-22', , );
INSERT INTO account(id, acc_type_id, entity_id, name, code, description, d_created, parent, children) values (6, 10, 1,  '10% Service Charge',  '',  '',  '2012-08-22', , );
TRUNCATE table account_type;
INSERT INTO account_type(id, name) values (1, 'Fixed Assets');
INSERT INTO account_type(id, name) values (2, 'Account Payable');
INSERT INTO account_type(id, name) values (3, 'Account Receivable');
INSERT INTO account_type(id, name) values (4, 'Other Current Liabilities');
INSERT INTO account_type(id, name) values (5, 'Other Current Assets');
INSERT INTO account_type(id, name) values (6, 'Long Term Liabilities');
INSERT INTO account_type(id, name) values (7, 'Expenses');
INSERT INTO account_type(id, name) values (8, 'Equity');
INSERT INTO account_type(id, name) values (9, 'Sales Retuns and Allowances');
INSERT INTO account_type(id, name) values (10, 'Income');
INSERT INTO account_type(id, name) values (11, 'Opening Stock');
INSERT INTO account_type(id, name) values (12, 'Purchases Retuns and Allowances');
INSERT INTO account_type(id, name) values (13, 'Purchases');
INSERT INTO account_type(id, name) values (15, 'Closing Stock');
TRUNCATE table charges;
INSERT INTO charges(id, name, type, amount, acc_id) values (1,  '5% Tax',  'percentage_of_room_rate',  '5', 5);
INSERT INTO charges(id, name, type, amount, acc_id) values (2,  '10% Service Charge',  'percentage_of_room_rate',  '10', 6);
TRUNCATE table department;
INSERT INTO department(id, name) values (1, 'Room');
INSERT INTO department(id, name) values (2, 'Restaurant');
INSERT INTO department(id, name) values (3, 'Laundry');
TRUNCATE table hotel_info;
INSERT INTO hotel_info(id, name, address, phone, email, web) values (1,  'Mimah Suites',  'wherver',  '',  '', '');
TRUNCATE table permissions;
INSERT INTO permissions(id, name) values (1, 'Manager');
INSERT INTO permissions(id, name) values (2, 'Accountant');
INSERT INTO permissions(id, name) values (3, 'Front Office Cashier');
INSERT INTO permissions(id, name) values (4, 'Restaurant Cashier');
INSERT INTO permissions(id, name) values (5, 'Reception');
TRUNCATE table room;
INSERT INTO room(id, number, room_category_id, occupancy, status, comment, picture1, picture2, account_id) values (1,  '101', 1,  'Vacant',  'Clean',  '',  '',  '', );
TRUNCATE table room_category;
INSERT INTO room_category(id, name, rate, deposit) values (1,  'Queens',  '10000', '12000');
TRUNCATE table user;
INSERT INTO user(id, username, password) values (1,  'admin', '5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8');
TRUNCATE table user_permissions;
INSERT INTO user_permissions(id, uid, pid) values (1, 1, 1);
